In [4]:
import pandas as pd
import numpy as np
import requests
from pprint import pprint

In [5]:
df = pd.read_csv("static/22_23_Jun.csv")
df

,_id,resale_price,year,month,timeseries_month,region,town,rooms,avg_storey,floor_area_sqm,remaining_lease,address,dist_to_marina_bay,latitude,longitude,postal_code,nearest_station_0,dist_to_station_0
0,154888,788000.0,2023,6,2023-06-01,Central,Geylang,4.0,11.0,104.0,60.500000,"58, Dakota Cres",4.03,1.307307,103.889390,390058,Dakota MRT,0.14
1,154887,875000.0,2023,6,2023-06-01,Central,Geylang,4.0,17.0,93.0,92.500000,"17B, Circuit Road",5.91,1.329940,103.889189,372017,MacPherson MRT,0.42
2,154886,770000.0,2023,6,2023-06-01,Central,Geylang,4.0,5.0,93.0,92.583333,"18D, Circuit Road",5.86,1.329404,103.889197,374018,MacPherson MRT,0.36
3,154885,300000.0,2023,6,2023-06-01,Central,Geylang,3.0,5.0,58.0,48.333333,"91, Paya Lebar Way",5.09,1.322681,103.886738,370091,MacPherson MRT,0.48
4,154884,295000.0,2023,6,2023-06-01,Central,Geylang,3.0,2.0,58.0,48.333333,"91, Paya Lebar Way",5.09,1.322681,103.886738,370091,MacPherson MRT,0.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39140,117232,439888.0,2022,1,2022-01-01,West,Choa Chu Kang,4.0,14.0,102.0,76.500000,"296A, Choa Chu Kang Avenue 2",16.83,1.377142,103.740943,681296,Choa Chu Kang MRT,0.99
39141,117231,420000.0,2022,1,2022-01-01,West,Choa Chu Kang,4.0,5.0,104.0,72.000000,"252, Choa Chu Kang Avenue 2",16.53,1.378035,103.745021,680252,Choa Chu Kang MRT,0.81
39142,117230,410000.0,2022,1,2022-01-01,West,Choa Chu Kang,4.0,2.0,101.0,76.500000,"297C, Choa Chu Kang Avenue 2",16.68,1.377808,103.743067,683297,Choa Chu Kang MRT,0.85
39143,117369,400000.0,2022,1,2022-01-01,West,Clementi,3.0,11.0,67.0,55.500000,"334, Clementi Avenue 2",10.84,1.315185,103.768433,120334,Clementi MRT,0.36
39144,117229,425000.0,2022,1,2022-01-01,West,Choa Chu Kang,4.0,2.0,104.0,67.416667,"295, Choa Chu Kang Avenue 2",16.89,1.378166,103.740968,680295,Choa Chu Kang MRT,0.88

## Errors
There are two wrong API calls involving two addresses

In [19]:
df[df['address'].str.contains('Marine Cres')]

,_id,resale_price,year,month,timeseries_month,region,town,rooms,avg_storey,floor_area_sqm,remaining_lease,address,dist_to_marina_bay,latitude,longitude,postal_code,nearest_station_0,dist_to_station_0
1107,155099,910088.0,2023,6,2023-06-01,Central,Marine Parade,5.0,20.0,117.0,51.500000,"43, Marine Cres",6.23,1.305519,103.913022,440043,Kembangan MRT,1.72
1111,155095,400000.0,2023,6,2023-06-01,Central,Marine Parade,3.0,8.0,65.0,51.166667,"47, Marine Cres",6.19,1.305724,103.912531,440047,Kembangan MRT,1.69
3409,153341,1000000.0,2023,5,2023-05-01,Central,Marine Parade,5.0,11.0,126.0,50.916667,"27, Marine Cres",24.34,1.314112,103.644248,638741,Tuas Crescent MRT,0.93
3410,153340,740000.0,2023,5,2023-05-01,Central,Marine Parade,5.0,11.0,117.0,51.583333,"43, Marine Cres",6.23,1.305519,103.913022,440043,Kembangan MRT,1.72
3411,153339,950000.0,2023,5,2023-05-01,Central,Marine Parade,5.0,23.0,126.0,50.916667,"28, Marine Cres",6.18,1.303437,103.913349,440028,Kembangan MRT,1.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33618,122197,420000.0,2022,3,2022-03-01,Central,Marine Parade,3.0,2.0,65.0,52.166667,"33, Marine Cres",6.03,1.302649,103.912185,440033,Kembangan MRT,2.04
35208,120059,540000.0,2022,2,2022-02-01,Central,Marine Parade,4.0,5.0,88.0,52.250000,"45, Marine Cres",6.13,1.304550,103.912456,440045,Kembangan MRT,1.82
38469,117901,740000.0,2022,1,2022-01-01,Central,Marine Parade,5.0,11.0,120.0,52.916667,"43, Marine Cres",6.23,1.305519,103.913022,440043,Kembangan MRT,1.72
38474,117896,448000.0,2022,1,2022-01-01,Central,Marine Parade,4.0,2.0,82.0,52.333333,"34, Marine Cres",6.08,1.304150,103.912124,440034,Kembangan MRT,1.87
38476,117894,495000.0,2022,1,2022-01-01,Central,Marine Parade,3.0,17.0,76.0,52.416667,"32, Marine Cres",6.01,1.303178,103.911807,440032,Kembangan MRT,1.98

In [18]:
df[df['address'].str.contains('Jln Batu')]

,_id,resale_price,year,month,timeseries_month,region,town,rooms,avg_storey,floor_area_sqm,remaining_lease,address,dist_to_marina_bay,latitude,longitude,postal_code,nearest_station_0,dist_to_station_0
1107,155099,910088.0,2023,6,2023-06-01,Central,Marine Parade,5.0,20.0,117.0,51.500000,"43, Marine Cres",6.23,1.305519,103.913022,440043,Kembangan MRT,1.72
1111,155095,400000.0,2023,6,2023-06-01,Central,Marine Parade,3.0,8.0,65.0,51.166667,"47, Marine Cres",6.19,1.305724,103.912531,440047,Kembangan MRT,1.69
3409,153341,1000000.0,2023,5,2023-05-01,Central,Marine Parade,5.0,11.0,126.0,50.916667,"27, Marine Cres",24.34,1.314112,103.644248,638741,Tuas Crescent MRT,0.93
3410,153340,740000.0,2023,5,2023-05-01,Central,Marine Parade,5.0,11.0,117.0,51.583333,"43, Marine Cres",6.23,1.305519,103.913022,440043,Kembangan MRT,1.72
3411,153339,950000.0,2023,5,2023-05-01,Central,Marine Parade,5.0,23.0,126.0,50.916667,"28, Marine Cres",6.18,1.303437,103.913349,440028,Kembangan MRT,1.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33618,122197,420000.0,2022,3,2022-03-01,Central,Marine Parade,3.0,2.0,65.0,52.166667,"33, Marine Cres",6.03,1.302649,103.912185,440033,Kembangan MRT,2.04
35208,120059,540000.0,2022,2,2022-02-01,Central,Marine Parade,4.0,5.0,88.0,52.250000,"45, Marine Cres",6.13,1.304550,103.912456,440045,Kembangan MRT,1.82
38469,117901,740000.0,2022,1,2022-01-01,Central,Marine Parade,5.0,11.0,120.0,52.916667,"43, Marine Cres",6.23,1.305519,103.913022,440043,Kembangan MRT,1.72
38474,117896,448000.0,2022,1,2022-01-01,Central,Marine Parade,4.0,2.0,82.0,52.333333,"34, Marine Cres",6.08,1.304150,103.912124,440034,Kembangan MRT,1.87
38476,117894,495000.0,2022,1,2022-01-01,Central,Marine Parade,3.0,17.0,76.0,52.416667,"32, Marine Cres",6.01,1.303178,103.911807,440032,Kembangan MRT,1.98

In [6]:
central = df['region']=='Central'
central_district_mrt = [
    "Bishan MRT",
    "Tiong Bahru MRT",
    "Redhill MRT",
    "Queenstown MRT",
    "Toa Payoh MRT",
    "Tai Seng MRT",
    "Bartley MRT",
    "Serangoon MRT",
    "Lorong Chuan MRT",
    "Bishan MRT",
    "Dhoby Ghaut MRT",
    "Bras Basah MRT",
    "Esplanade MRT",
    "Promenade MRT",
    "Nicoll Highway MRT",
    "Lavender MRT",
    "Mountbatten MRT",
    "Dakota MRT",
    "Paya Lebar MRT",
    "MacPherson MRT",
    "Marymount MRT",
    "Newton MRT",
    "Downtown MRT",
    "Rochor MRT",
    "Bugis MRT",
    "Promenade MRT",
    "Bayfront MRT",
    "City Hall MRT",
    "Downtown MRT",
    "Telok Ayer MRT",
    "Chinatown MRT",
    "Fort Canning MRT",
    "Bencoolen MRT",
    "Jalan Besar MRT",
    "Bendemeer MRT",
    "Geylang Bahru MRT",
    "Potong Pasir MRT",
    "Kaki Bukit MRT",
    "Eunos MRT",
    'Mattar MRT',
    'Tanjong Pagar MRT',
    'Little India MRT',
    'Outram Park MRT',
    'Holland Village MRT',
    'Telok Blangah MRT',
    'Ubi MRT',
    'Aljunied MRT',
    'Botanic Gardens MRT',
    'Labrador Park MRT',
    'Keppel MRT',
    'HarbourFront MRT',
    'Boon Keng MRT',
    'Farrer Park MRT',
    'Ang Mo Kio MRT',
    'Upper Thomson MRT',
    'Braddell MRT',
    'Kallang MRT',
    'Caldecott MRT',
    'Kembangan MRT',
    'Commonwealth MRT',
    'Buona Vista MRT',
    'Beauty World MRT',
    'One-North MRT',
    'Novena MRT',
    'Mayflower MRT',
    'Clarke Quay MRT',
    'King Albert Park MRT',
    'Haw Par Villa MRT'
    
]
central_district_mrt = set(central_district_mrt)

central_mrts = ~df['nearest_station_0'].isin(central_district_mrt)

In [7]:
error_df = df[central & central_mrts]
error_df

,_id,resale_price,year,month,timeseries_month,region,town,rooms,avg_storey,floor_area_sqm,remaining_lease,address,dist_to_marina_bay,latitude,longitude,postal_code,nearest_station_0,dist_to_station_0
1137,155069,330000.0,2023,6,2023-06-01,Central,Kallang/Whampoa,3.0,5.0,60.0,44.583333,"6, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13
3409,153341,1000000.0,2023,5,2023-05-01,Central,Marine Parade,5.0,11.0,126.0,50.916667,"27, Marine Cres",24.34,1.314112,103.644248,638741,Tuas Crescent MRT,0.93
3491,153258,300000.0,2023,5,2023-05-01,Central,Kallang/Whampoa,2.0,8.0,50.0,46.083333,"7, Jln Batu",16.55,1.392531,103.757872,679531,Yew Tee MRT,1.29
4745,151073,315000.0,2023,4,2023-04-01,Central,Kallang/Whampoa,3.0,11.0,60.0,44.750000,"6, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13
4746,151072,330000.0,2023,4,2023-04-01,Central,Kallang/Whampoa,3.0,8.0,60.0,44.750000,"6, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13
10306,144670,750000.0,2023,1,2023-01-01,Central,Marine Parade,5.0,14.0,123.0,51.166667,"27, Marine Cres",24.34,1.314112,103.644248,638741,Tuas Crescent MRT,0.93
10389,144587,334000.0,2023,1,2023-01-01,Central,Kallang/Whampoa,3.0,8.0,60.0,45.083333,"3, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13
10406,144570,278000.0,2023,1,2023-01-01,Central,Kallang/Whampoa,2.0,8.0,50.0,46.500000,"7, Jln Batu",16.55,1.392531,103.757872,679531,Yew Tee MRT,1.29
13624,142198,910000.0,2022,12,2022-12-01,Central,Marine Parade,5.0,23.0,126.0,51.333333,"27, Marine Cres",24.34,1.314112,103.644248,638741,Tuas Crescent MRT,0.93
15799,140017,826800.0,2022,11,2022-11-01,Central,Marine Parade,5.0,8.0,126.0,51.500000,"27, Marine Cres",24.34,1.314112,103.644248,638741,Tuas Crescent MRT,0.93
15862,139956,320000.0,2022,11,2022-11-01,Central,Kallang/Whampoa,3.0,2.0,60.0,45.250000,"3, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13
18555,137930,310000.0,2022,10,2022-10-01,Central,Kallang/Whampoa,3.0,5.0,60.0,45.333333,"6, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13
22696,133268,340000.0,2022,8,2022-08-01,Central,Kallang/Whampoa,3.0,5.0,60.0,45.500000,"6, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13
24945,130877,300000.0,2022,7,2022-07-01,Central,Kallang/Whampoa,3.0,2.0,60.0,45.583333,"6, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13
29123,126528,272000.0,2022,5,2022-05-01,Central,Kallang/Whampoa,2.0,8.0,48.0,47.166667,"7, Jln Batu",16.55,1.392531,103.757872,679531,Yew Tee MRT,1.29
32546,122209,800000.0,2022,3,2022-03-01,Central,Marine Parade,5.0,8.0,126.0,52.000000,"27, Marine Cres",24.34,1.314112,103.644248,638741,Tuas Crescent MRT,0.93
35275,119993,310000.0,2022,2,2022-02-01,Central,Kallang/Whampoa,3.0,5.0,60.0,46.000000,"3, Jln Batu",16.66,1.391731,103.755741,678673,Yew Tee MRT,1.13

In [12]:
def get_location_data(address_df: pd.DataFrame, verbose=0):
    '''
    Function to carry out API call for Geodata
    ## Parameters
    address_df : pd.DataFrame
        DataFrame that contains a combination of ['block'] and ['street_name'] as ['address'], and ['town']
    verbose : int
        1 to verbose calls
    '''
    # Getting latitude, longitude, postal code
    def get_lat_long(address_df : pd.DataFrame, sleeptime : float =0.15):
        '''
        The actual API call to be called row-wise to get latitude, longitude, and postal code
        ## Parameters
        address_df : pd.DataFrame
            DataFrame that contains a combination of ['block'] and ['street_name'] as ['address'], and ['town']
        sleeptime : float
            Incorporates sleep time to not exceed a max of 250 calls per min
            Default 0.15s, not required if we are caching call
        '''
        
        # Lag time between calls - No longer needed with Cache, since we will not likely exceed the call limit
        # time.sleep(sleeptime)

        # API call
        try:
            address = address_df['address']
            if 'Jln Batu' in address:
                address = address.replace('Jln Batu', 'JALAN BATU DI TANJONG RHU')
            elif 'Marine Cres' in address:
                address = address.replace('Marine Cres', 'MARINE CRESCENT MARINE CRESCENT VILLE')
            call = f'https://developers.onemap.sg/commonapi/search?searchVal={address}&returnGeom=Y&getAddrDetails=Y'
            # Caching is enabled in the session
            response = requests.get(call)
            response.raise_for_status()
            data = response.json()
            if verbose >0:
                print(call)
                pprint(data)

            # Returns a the results in string
            return data['results'][0]['LATITUDE'] + ',' + data['results'][0]['LONGITUDE'] + ' ' + data['results'][0]['POSTAL']
        
        except Exception as err:
            print(f'Error occurred - get_lat_long() API call: {err} on the following call:')
            pprint(call)
            return '0,0 0' # Still return 0 values

    def to_numpy_array(lat_long_df):
        # Build a numpy array from latitude and longitude
        combi = np.array([lat_long_df[0], lat_long_df[1]])
        return combi
    
    # This calls the API call function row wise
    position = address_df.apply(get_lat_long, axis=1)

    try:
        # Split the string into two columns (column 0 is the latitude and longitude, column 1 is the postal code)
        temp_df = position.str.split(expand=True)
        # Postal code
        temp_df.iloc[:,1] = temp_df.iloc[:,1].apply(lambda x: 0 if x=='NIL' else x)
        temp_df.iloc[:,1] = temp_df.iloc[:,1].astype('int')
        # Latitude and longitude split (by ,)
        lat_long_df = temp_df.iloc[:,0].str.split(pat=',', expand=True)
        lat_long_df = lat_long_df.astype('float')
        # Convert into numpy array, for faster matrix operations later
        numpy_array = lat_long_df.apply(to_numpy_array, axis=1)
        
    except Exception as err:
        print(f"Error occurred - Splitting data : {err}")
    else:
        geo_data_df = pd.concat([temp_df, lat_long_df, numpy_array], axis=1)
        geo_data_df.columns = ['lat_long', 'postal_code', 'latitude', 'longitude', 'numpy_array']
        return geo_data_df

In [13]:
geo_data_df= get_location_data(error_df[['address', 'town']])
display(geo_data_df.dtypes)
geo_data_df

https://developers.onemap.sg/commonapi/search?searchVal=6, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '6 JALAN BATU DI TANJONG RHU SINGAPORE 431006',
              'BLK_NO': '6',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30129028933217',
              'LONGITUDE': '103.884012115114',
              'LONGTITUDE': '103.884012115114',
              'POSTAL': '431006',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33641.7336952556',
              'Y': '31515.6437175125'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=27, MARINE CRESCENT MARINE CRESCENT VILLE&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '27 MARINE CRESCENT MARINE CRESCENT VILLE SINGAPORE '
                         '440027',
              'BLK_NO': '27',
              'BUILDING': 'MARINE CRESCENT VILLE',
              'LATITUDE': '1.30402508947699',
              'LONGITUDE': '103.913501458863',
              'LONGTITUDE': '103.913501458863',
              'POSTAL': '440027',
              'ROAD_NAME': 'MARINE CRESCENT',
              'SEARCHVAL': 'MARINE CRESCENT VILLE',
              'X': '36923.6240353324',
              'Y': '31818.1292342301'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=7, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '7 JALAN BATU DI TANJONG RHU SINGAPORE 431007',
              'BLK_NO': '7',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30237002555566',
              'LONGITUDE': '103.88359641393',
              'LONGTITUDE': '103.88359641393',
              'POSTAL': '431007',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33595.467508208',
              'Y': '31635.0345080309'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=6, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '6 JALAN BATU DI TANJONG RHU SINGAPORE 431006',
              'BLK_NO': '6',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30129028933217',
              'LONGITUDE': '103.884012115114',
              'LONGTITUDE': '103.884012115114',
              'POSTAL': '431006',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33641.7336952556',
              'Y': '31515.6437175125'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=6, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '6 JALAN BATU DI TANJONG RHU SINGAPORE 431006',
              'BLK_NO': '6',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30129028933217',
              'LONGITUDE': '103.884012115114',
              'LONGTITUDE': '103.884012115114',
              'POSTAL': '431006',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33641.7336952556',
              'Y': '31515.6437175125'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=27, MARINE CRESCENT MARINE CRESCENT VILLE&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '27 MARINE CRESCENT MARINE CRESCENT VILLE SINGAPORE '
                         '440027',
              'BLK_NO': '27',
              'BUILDING': 'MARINE CRESCENT VILLE',
              'LATITUDE': '1.30402508947699',
              'LONGITUDE': '103.913501458863',
              'LONGTITUDE': '103.913501458863',
              'POSTAL': '440027',
              'ROAD_NAME': 'MARINE CRESCENT',
              'SEARCHVAL': 'MARINE CRESCENT VILLE',
              'X': '36923.6240353324',
              'Y': '31818.1292342301'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=3, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '3 JALAN BATU DI TANJONG RHU SINGAPORE 431003',
              'BLK_NO': '3',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30288393170238',
              'LONGITUDE': '103.883934229235',
              'LONGTITUDE': '103.883934229235',
              'POSTAL': '431003',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33633.0621600635',
              'Y': '31691.8603773601'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=7, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '7 JALAN BATU DI TANJONG RHU SINGAPORE 431007',
              'BLK_NO': '7',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30237002555566',
              'LONGITUDE': '103.88359641393',
              'LONGTITUDE': '103.88359641393',
              'POSTAL': '431007',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33595.467508208',
              'Y': '31635.0345080309'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=27, MARINE CRESCENT MARINE CRESCENT VILLE&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '27 MARINE CRESCENT MARINE CRESCENT VILLE SINGAPORE '
                         '440027',
              'BLK_NO': '27',
              'BUILDING': 'MARINE CRESCENT VILLE',
              'LATITUDE': '1.30402508947699',
              'LONGITUDE': '103.913501458863',
              'LONGTITUDE': '103.913501458863',
              'POSTAL': '440027',
              'ROAD_NAME': 'MARINE CRESCENT',
              'SEARCHVAL': 'MARINE CRESCENT VILLE',
              'X': '36923.6240353324',
              'Y': '31818.1292342301'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=27, MARINE CRESCENT MARINE CRESCENT VILLE&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '27 MARINE CRESCENT MARINE CRESCENT VILLE SINGAPORE '
                         '440027',
              'BLK_NO': '27',
              'BUILDING': 'MARINE CRESCENT VILLE',
              'LATITUDE': '1.30402508947699',
              'LONGITUDE': '103.913501458863',
              'LONGTITUDE': '103.913501458863',
              'POSTAL': '440027',
              'ROAD_NAME': 'MARINE CRESCENT',
              'SEARCHVAL': 'MARINE CRESCENT VILLE',
              'X': '36923.6240353324',
              'Y': '31818.1292342301'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=3, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '3 JALAN BATU DI TANJONG RHU SINGAPORE 431003',
              'BLK_NO': '3',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30288393170238',
              'LONGITUDE': '103.883934229235',
              'LONGTITUDE': '103.883934229235',
              'POSTAL': '431003',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33633.0621600635',
              'Y': '31691.8603773601'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=6, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '6 JALAN BATU DI TANJONG RHU SINGAPORE 431006',
              'BLK_NO': '6',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30129028933217',
              'LONGITUDE': '103.884012115114',
              'LONGTITUDE': '103.884012115114',
              'POSTAL': '431006',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33641.7336952556',
              'Y': '31515.6437175125'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=6, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '6 JALAN BATU DI TANJONG RHU SINGAPORE 431006',
              'BLK_NO': '6',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30129028933217',
              'LONGITUDE': '103.884012115114',
              'LONGTITUDE': '103.884012115114',
              'POSTAL': '431006',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33641.7336952556',
              'Y': '31515.6437175125'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=6, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '6 JALAN BATU DI TANJONG RHU SINGAPORE 431006',
              'BLK_NO': '6',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30129028933217',
              'LONGITUDE': '103.884012115114',
              'LONGTITUDE': '103.884012115114',
              'POSTAL': '431006',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33641.7336952556',
              'Y': '31515.6437175125'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=7, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '7 JALAN BATU DI TANJONG RHU SINGAPORE 431007',
              'BLK_NO': '7',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30237002555566',
              'LONGITUDE': '103.88359641393',
              'LONGTITUDE': '103.88359641393',
              'POSTAL': '431007',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33595.467508208',
              'Y': '31635.0345080309'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=27, MARINE CRESCENT MARINE CRESCENT VILLE&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '27 MARINE CRESCENT MARINE CRESCENT VILLE SINGAPORE '
                         '440027',
              'BLK_NO': '27',
              'BUILDING': 'MARINE CRESCENT VILLE',
              'LATITUDE': '1.30402508947699',
              'LONGITUDE': '103.913501458863',
              'LONGTITUDE': '103.913501458863',
              'POSTAL': '440027',
              'ROAD_NAME': 'MARINE CRESCENT',
              'SEARCHVAL': 'MARINE CRESCENT VILLE',
              'X': '36923.6240353324',
              'Y': '31818.1292342301'}],
 'totalNumPages': 1}
https://developers.onemap.sg/commonapi/search?searchVal=3, JALAN BATU DI TANJONG RHU&returnGeom=Y&getAddrDetails=Y
{'found': 1,
 'pageNum': 1,
 'results': [{'ADDRESS': '3 JALAN BATU DI TANJONG RHU SINGAPORE 431003',
              'BLK_NO': '3',
              'BUILDING': 'DI TANJONG RHU',
              'LATITUDE': '1.30288393170238',
              'LONGITUDE': '103.883934229235',
              'LONGTITUDE': '103.883934229235',
              'POSTAL': '431003',
              'ROAD_NAME': 'JALAN BATU',
              'SEARCHVAL': 'DI TANJONG RHU',
              'X': '33633.0621600635',
              'Y': '31691.8603773601'}],
 'totalNumPages': 1}

lat_long        object
postal_code     object
latitude       float64
longitude      float64
numpy_array     object
dtype: object

,lat_long,postal_code,latitude,longitude,numpy_array
1137,"1.30129028933217,103.884012115114",431006,1.301290,103.884012,"[1.30129028933217, 103.884012115114]"
3409,"1.30402508947699,103.913501458863",440027,1.304025,103.913501,"[1.30402508947699, 103.913501458863]"
3491,"1.30237002555566,103.88359641393",431007,1.302370,103.883596,"[1.30237002555566, 103.88359641393]"
4745,"1.30129028933217,103.884012115114",431006,1.301290,103.884012,"[1.30129028933217, 103.884012115114]"
4746,"1.30129028933217,103.884012115114",431006,1.301290,103.884012,"[1.30129028933217, 103.884012115114]"
10306,"1.30402508947699,103.913501458863",440027,1.304025,103.913501,"[1.30402508947699, 103.913501458863]"
10389,"1.30288393170238,103.883934229235",431003,1.302884,103.883934,"[1.30288393170238, 103.883934229235]"
10406,"1.30237002555566,103.88359641393",431007,1.302370,103.883596,"[1.30237002555566, 103.88359641393]"
13624,"1.30402508947699,103.913501458863",440027,1.304025,103.913501,"[1.30402508947699, 103.913501458863]"
15799,"1.30402508947699,103.913501458863",440027,1.304025,103.913501,"[1.30402508947699, 103.913501458863]"
15862,"1.30288393170238,103.883934229235",431003,1.302884,103.883934,"[1.30288393170238, 103.883934229235]"
18555,"1.30129028933217,103.884012115114",431006,1.301290,103.884012,"[1.30129028933217, 103.884012115114]"
22696,"1.30129028933217,103.884012115114",431006,1.301290,103.884012,"[1.30129028933217, 103.884012115114]"
24945,"1.30129028933217,103.884012115114",431006,1.301290,103.884012,"[1.30129028933217, 103.884012115114]"
29123,"1.30237002555566,103.88359641393",431007,1.302370,103.883596,"[1.30237002555566, 103.88359641393]"
32546,"1.30402508947699,103.913501458863",440027,1.304025,103.913501,"[1.30402508947699, 103.913501458863]"
35275,"1.30288393170238,103.883934229235",431003,1.302884,103.883934,"[1.30288393170238, 103.883934229235]"